```{r}
# 1. Library (must be installed prior to loading
library(RMySQL)     ### MySQL

#2. CSV File Name:
file_csv <- '/Users/sanyamharne/Desktop/Practicum1/'

# 4. Settings
db_user <- 'root'
db_password <- 'Password@123'
db_name <- 'practicum1'

# Local: localhost
db_host <- 'localhost' 
db_port <- 3306 # always this port unless you change it during installation

# 4. Connect to DB
mydb <-  dbConnect(MySQL(), user = db_user, password = db_password,
                dbname = db_name, host = db_host, port = db_port)
dbListTables(mydb)
```


```{r}
query<- ("DROP TABLE IF EXISTS practicum1.`bird_strike_incident`;");
dbSendQuery(mydb, query);
query<- ("DROP TABLE IF EXISTS practicum1.`airport`;");
dbSendQuery(mydb, query);
query<- ("DROP TABLE IF EXISTS practicum1.`precipitation`;");
dbSendQuery(mydb, query);
query<- ("DROP TABLE IF EXISTS practicum1.`precipitation_type`;");
dbSendQuery(mydb, query);
query<- ("DROP TABLE IF EXISTS practicum1.`wildlife`;");
dbSendQuery(mydb, query);
query<- ("DROP TABLE IF EXISTS practicum1.`airline_aircrafts`;");
dbSendQuery(mydb, query);
query<-("DROP TABLE IF EXISTS practicum1.`airline_operator`;");
dbSendQuery(mydb, query);
query<-("DROP TABLE IF EXISTS practicum1.`aircraft`;");
dbSendQuery(mydb, query);
dbListTables(mydb);
```

```{r}
query<-("
  CREATE TABLE IF NOT EXISTS practicum1.`aircraft` (
  `AircraftTypeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) DEFAULT ' ',
  `Make_Model` VARCHAR(45) DEFAULT ' ',
  `IsAircraftLarge` TINYINT DEFAULT 0,
  CONSTRAINT unique_constraint UNIQUE(Type,Make_Model,IsAircraftLarge),
  PRIMARY KEY (`AircraftTypeID`));
");

dbSendQuery(mydb, query);
```

```{r}
dbListTables(mydb)
```

```{r}
query<-("
  CREATE TABLE IF NOT EXISTS practicum1.`airline_operator` (
  `AirlineOperatorId` INT NOT NULL AUTO_INCREMENT,
  `AirlineOperator` VARCHAR(45) DEFAULT ' ' NULL UNIQUE,
  PRIMARY KEY (`AirlineOperatorId`));");

dbSendQuery(mydb, query);
```

```{r}
query <- ("
  CREATE TABLE IF NOT EXISTS practicum1.`airline_aircrafts` (
  `PlaneID` INT NOT NULL AUTO_INCREMENT,
  `AircraftTypeID` INT NULL,
  `AirlineOperatorID` INT NULL,
  `NumberOfEngines` INT  DEFAULT 0 NULL,
  CONSTRAINT unique_constraint UNIQUE (AircraftTypeID,AirlineOperatorID,NumberOfEngines),
  PRIMARY KEY (`PlaneID`),
  FOREIGN KEY (`AircraftTypeID`) REFERENCES practicum1.`aircraft` (`AircraftTypeID`),
  FOREIGN KEY (`AirlineOperatorID`) REFERENCES practicum1.`airline_operator` (`AirlineOperatorId`));
  
  ");


dbSendQuery(mydb, query)
```

```{r}
query <- ("
  CREATE TABLE IF NOT EXISTS practicum1.`wildlife` (
  `WildlifeID` INT NOT NULL AUTO_INCREMENT,
  `Species` VARCHAR(45) DEFAULT ' ' NULL,
  `Size` ENUM('Small', 'Medium', 'Large') DEFAULT 'Small' NULL,
  CONSTRAINT unique_constraint UNIQUE (Species, Size),
  PRIMARY KEY (`WildlifeID`));");

dbSendQuery(mydb, query)
```

```{r}
query <- ("
  CREATE TABLE IF NOT EXISTS practicum1.`precipitation_type` (
  `PrecipitationID` INT NOT NULL AUTO_INCREMENT,
  `Precipitation_Type` VARCHAR(45) DEFAULT ' ' NULL UNIQUE,
  PRIMARY KEY (`PrecipitationID`));");

dbSendQuery(mydb, query)
```

```{r}
query <- ("
  CREATE TABLE IF NOT EXISTS practicum1.`precipitation` (
  `RecordID` INT NOT NULL,
  `PrecipitationID` INT NOT NULL,
  PRIMARY KEY (`RecordID`, `PrecipitationID`),
  FOREIGN KEY (`PrecipitationID`) REFERENCES practicum1.`precipitation_type` (`PrecipitationID`));");

dbSendQuery(mydb, query)
```

```{r}
query <- ("
  CREATE TABLE IF NOT EXISTS practicum1.`airport` (
  `AirportID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) DEFAULT ' ' NULL,
  `State` VARCHAR(45) DEFAULT ' ' NULL,
  CONSTRAINT unique_constraint UNIQUE (Name,State),
  PRIMARY KEY (`AirportID`));");

dbSendQuery(mydb, query)
```

```{r}
query <- ('CREATE TABLE IF NOT EXISTS practicum1.`bird_strike_incident` (
  `RecordID` INT NOT NULL AUTO_INCREMENT,
  `FlightDate` DATETIME NULL,
  `WildLife_NumberOfStruck` VARCHAR(80) NULL,
  `WildLife_NumberOfStruckActual` INT NULL,
  `Effect_ImpactToFlight` VARCHAR(80) NULL,
  `Altitude_Bin` VARCHAR(10) NULL,
  `EffectIndicatedDamage` VARCHAR(20) NULL,
  `PhaseOfFlight` ENUM("Approach", "Climb", "Descent", "Landing Roll", "Take-off run", "Taxi") NULL,
  `WildLifeRemainsCollected` VARCHAR(50) NULL,
  `WildLifeRemainsSent` VARCHAR(50) NULL,
  `Remarks` LONGTEXT NULL,
  `PilotWarned` VARCHAR(50) NULL,
  `Cost_Total` INT NULL,
  `FeetAboveGround` INT NULL,
  `PeopleInjured` INT NULL,
  `ConditionsSky` VARCHAR(50) NULL,
  `PlaneID` INT NULL,
  `WildlifeID` INT NULL,
  `AirportID` INT NULL,
  PRIMARY KEY (`RecordID`),
  FOREIGN KEY (`PlaneID`) REFERENCES practicum1.`airline_aircrafts` (`PlaneID`),
  FOREIGN KEY (`WildlifeID`) REFERENCES practicum1.`wildlife` (`WildlifeID`),
  FOREIGN KEY (`AirportID`) REFERENCES practicum1.`airport` (`AirportID`));');

dbSendQuery(mydb, query);
```



```{r}
#dbListTables(mydb)
dbDisconnect(mydb)
```